name: Publish to Nuget Package Repository
    
on:
  push:
    branches:
      - main

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Check out branch
      uses: actions/checkout@v1
      with:
        ref: main
    - name: Set Up .NET Core
      uses: actions/setup-dotnet@v1      
    - name: Install Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
    - name: Publish to NuGet        
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: trnsACT.Data.csproj
        PACKAGE_NAME: trnsACT.Data
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.trnsACT_NUGET_KEY_EXP_20221130}}
